[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Panagiotis Matsinopoulos", email = "panagiotis@matsinopoulos.gr"},
]
dependencies = []
requires-python = ">=3.11"
license = {text = "MIT"}
